CREATE DATABASE test;

/*DROP TABLE ENTRIES;*/
CREATE TABLE entries(
	entry_id MEDIUMINT,
	corpus_title VARCHAR(50),
	corpus_body VARCHAR(12500),
	a1 VARCHAR(50),
	a2 VARCHAR(50),
	a3 VARCHAR(50),
	a4 VARCHAR(50),
	a5 VARCHAR(50),
	b1 VARCHAR(50),
	b2 VARCHAR(50),
	b3 VARCHAR(50),
	b4 VARCHAR(50),
	b5 VARCHAR(50),
	c1 VARCHAR(50),
	c2 VARCHAR(50),
	c3 VARCHAR(50),
	c4 VARCHAR(50),
	c5 VARCHAR(50)
);

/*DROP TABLE SELECTIONS;*/
CREATE TABLE selections(
	selection_id MEDIUMINT,
	entry_id MEDIUMINT,
	user_ip VARCHAR(12),
	selection_time DATETIME,
	a1 BOOLEAN,
	a2 BOOLEAN,
	a3 BOOLEAN,
	a4 BOOLEAN,
	a5 BOOLEAN,
	b1 BOOLEAN,
	b2 BOOLEAN,
	b3 BOOLEAN,
	b4 BOOLEAN,
	b5 BOOLEAN,
	c1 BOOLEAN,
	c2 BOOLEAN,
	c3 BOOLEAN,
	c4 BOOLEAN,
	c5 BOOLEAN
);